os:
  - linux
  - osx

language: cpp

matrix:
  include:
    - os: linux
      env: COMPILER=g++-11
    - os: osx
      env: COMPILER=clang++
      osx_image: xcode13

cache:
  ccache: true

script:
  - mkdir -p _build
  - cd _build
  - cmake ..
  - cmake --build .
  - ctest

jobs:
  include:
    - stage: Release
      script:
        - mkdir -p _build
        - cd _build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - cmake --build .
        - cpack -G "DEB"
        - cpack -G "RPM"
        - cpack -G "PackageMaker"

