platform:
  - x86
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

build_script:
  - mkdir _build
  - cd _build
  - cmake -G "Visual Studio 15 2017" -A x64 ..
  - cmake --build . --config Release

test_script:
  - ctest -C Release

artifacts:
  - path: _build\Release\solver.exe
    name: solver

deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  artifact: solver
  on:
    branch: master
    appveyor_repo_tag: true

