name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm dpkg cmake build-essential

      - name: Configure CMake
        run: cmake -S . -B build -DCPACK_GENERATOR="DEB;RPM"

      - name: Build
        run: cmake --build build

      - name: Package
        run: |
          cd build
          cpack -G DEB
          cpack -G RPM

      - name: Upload assets to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Solver Release ${{ github.ref_name }}
          body: Solver built from lab06 with DEB and RPM packages
          files: |
            build/*.deb
            build/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install nsis

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -S . -B build -DCPACK_GENERATOR="NSIS"

      - name: Build
        run: cmake --build build

      - name: Package
        run: |
          cd build

      - name: Create MSI package
        run: cpack -G NSIS

      - name: List build directory contents
        run: ls -R build

      - name: Upload assets to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Solver Release ${{ github.ref_name }}
          body: Solver built from lab06 with MSI package
          files: build/**/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install cmake

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -S . -B build -DCPACK_GENERATOR="DragNDrop"

      - name: Build
        run: cmake --build build

      - name: Create DMG package
        run: cd build && cpack -G DragNDrop

      - name: List build directory contents
        run: ls -R build

      - name: Upload DMG to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Solver Release ${{ github.ref_name }}
          body: Solver built from lab06 with DMG package
          files: build/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
